name: CMake
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CC: gcc-12
  CXX: g++-12
jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cmake --workflow --preset test